import React, { FormEvent, useEffect, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import CategoryContainer from '../components/CategoryContainer'
import styles from '../styles/Home.module.css'
import Category from '../interfaces/Category'
import Modal from '../components/Modal'

const Home: NextPage = () => {
  const [categories, setCategories] = useState([])
  const [isOpen, setOpen] = useState(false)
  const [formData, setFormData] = useState()
  const [reset, setReset] = useState(false)

  useEffect(() => {
    const getData = async () => {
      fetch('api/ballots')
      .then(response => response.json())
      .then(data => setCategories(data.items));
    }
    getData()
  }, [])

  const handleFormSubmit = (e: FormEvent) => {
    e.preventDefault()
    const target = e.target as HTMLFormElement
    const formData = new FormData(target)
    const data = Object.fromEntries(formData)
    for (let key in data) {
      try {
        const formattedData = JSON.parse(data[key] as string)
        data[key] = formattedData
      } catch (err) {
        continue
      }
    }
    setFormData(data as any)
    setOpen(true)
    setReset(false)
  };

  const handleClose = () => {
    setOpen(false)
    setReset(true)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Awards 2022
        </h1>
        <form onSubmit={handleFormSubmit}>
        {
          categories.map((category: Category, index) => (
            <CategoryContainer key={index} category={category} reset={reset}/>
          ))
        }
        <button type="submit" className={styles.submitBtn} onClick={() => setOpen(true)}>Sumbit Ballot Button</button>
        </form>
      </main>
      {isOpen && <Modal formData={formData} handleClose={() => handleClose()}/>}
    </div>
  )
}

export default Home
